central:
  name: stackrox-central-services
  scannerV4: Enabled

demoSizing:
  enabled: false

securedCluster:
  enabled: false
  name: stackrox-secured-cluster-services
  clusterName: customer-hub
  centralEndpoint: central.stackrox.svc:443
  collection: CORE_BPF
