global:
  openshift: true

injector:
  enabled: false

server:
  image:
    repository: INTERNAL_REGISTRY/hashicorp/vault
    tag: APPROVED_TAG
    pullPolicy: IfNotPresent
  route:
    enabled: true
    activeService: false
    host: vault.apps.CUSTOMER_CLUSTER_DOMAIN
    tls:
      termination: edge
  dataStorage:
    enabled: true
    size: 20Gi
    storageClass: APPROVED_RWO_STORAGE_CLASS
  auditStorage:
    enabled: true
    size: 10Gi
    storageClass: APPROVED_RWO_STORAGE_CLASS
  standalone:
    enabled: false
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        storage "raft" {
          path = "/vault/data"
          retry_join {
            leader_api_addr = "http://vault-0.vault-internal:8200"
          }
          retry_join {
            leader_api_addr = "http://vault-1.vault-internal:8200"
          }
          retry_join {
            leader_api_addr = "http://vault-2.vault-internal:8200"
          }
        }
        service_registration "kubernetes" {}
  readinessProbe:
    enabled: true
    path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204

ui:
  enabled: true
  serviceType: ClusterIP

csi:
  enabled: false
