apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: dotnet-sample-security-test-
  namespace: customer-cicd
spec:
  pipelineRef:
    name: application-release
  taskRunTemplate:
    serviceAccountName: pipeline
  params:
    - name: source-url
      value: https://github.com/waleed-nabeeh/appdev.git
    - name: source-revision
      value: develop
    - name: dotnet-project
      value: apps/dotnet-sample/src/Customer.Sample.Api/Customer.Sample.Api.csproj
    - name: image
      value: demo-registry-quay-quay-enterprise.apps.cluster-zmzbt.dyn.redhatworkshops.io/customer/dotnet-sample:demo-test
    - name: build-context
      value: apps/dotnet-sample
    - name: containerfile
      value: apps/dotnet-sample/Containerfile
    - name: gitops-url
      value: https://github.com/waleed-nabeeh/appdev.git
    - name: values-file
      value: apps/dotnet-sample/helm/values.yaml
    - name: perform-gitops-update
      value: "false"
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 2Gi
    - name: registry-auth
      secret:
        secretName: registry-auth
