replicaCount: 1

image:
  repository: demo-registry-quay-quay-enterprise.apps.cluster-zmzbt.dyn.redhatworkshops.io/customer/dotnet-sample
  tag: develop
  digest: sha256:97d34a37e6ceda3595370920faf23c8741fad8f15783cfb14a6e5b7cd9c72d75
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: quay-pull-secret

service:
  port: 8080

route:
  enabled: true
  host: ""
  tls:
    termination: edge

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
