replicaCount: 1

image:
  repository: image-registry.openshift-image-registry.svc:5000/customer-demo/customer-dotnet-sample
  tag: develop
  digest: ""
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: quay-pull-secret

service:
  port: 8080

route:
  enabled: true
  host: ""
  tls:
    termination: edge

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
