replicaCount: 1

image:
  repository: demo-registry-quay-quay-enterprise.apps.cluster-zmzbt.dyn.redhatworkshops.io/customer/dotnet-sample
  tag: develop
  digest: sha256:375728838ef115304102991e3d6404dd941047ce6f76117410908d0023554536
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: quay-pull-secret

service:
  port: 8080

route:
  enabled: true
  host: ""
  tls:
    termination: edge

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
