serviceAccount:
  name: pipeline

images:
  git: docker.io/alpine/git:latest
  dotnet: registry.access.redhat.com/ubi9/dotnet-100:latest
  buildah: registry.redhat.io/rhel9/buildah:latest
  skopeo: registry.redhat.io/rhel9/skopeo:latest
  rhacs: registry.redhat.io/advanced-cluster-security/rhacs-roxctl-rhel9:4.11
  rhtasClientServer: registry.redhat.io/rhtas/client-server-rhel9@sha256:3d08a27f79bda1f19369786723cb8d1e130c3d46cbb8a7f44e30571d5a213240

rhtas:
  audience: trusted-artifact-signer
  clientUrl: http://cli-server.trusted-artifact-signer.svc:8080
  certificateIdentityRegexp: ^https://kubernetes.io/namespaces/customer-cicd/serviceaccounts/pipeline$
  certificateOidcIssuer: https://kubernetes.default.svc
  fulcioUrl: https://fulcio-server-trusted-artifact-signer.apps.example.com
  rekorUrl: https://rekor-server-trusted-artifact-signer.apps.example.com
  tufUrl: https://tuf-trusted-artifact-signer.apps.example.com

rhacs:
  insecureSkipTLSVerify: false
