rhtas:
  fulcioUrl: https://fulcio-server-trusted-artifact-signer.apps.cluster-zmzbt.dyn.redhatworkshops.io
  rekorUrl: https://rekor-server-trusted-artifact-signer.apps.cluster-zmzbt.dyn.redhatworkshops.io
  tufUrl: https://tuf-trusted-artifact-signer.apps.cluster-zmzbt.dyn.redhatworkshops.io

rhacs:
  insecureSkipTLSVerify: true
